# This is a basic workflow to help you get started with Actions

name: Second workflow Terraform Destroy
on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token    : ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
          aws-region: ap-south-1

      
      - name: Terraform Init
        id  : init
        run : terraform init

      - name: Show Destroy plan
        run : terraform plan -destroy
        
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        
      


    
